dist: trusty
sudo: required
language: c

env:
  - GPG_VERSION=''
  - GPG_VERSION=2

addons:
  apt:
    packages:
      - zsh
      - cryptsetup
      - pinentry-curses
      - gawk
      - libgcrypt20-dev
      - steghide
      - qrencode
      - e2fsprogs

before_script:
  - sudo apt-get install -y gnupg$GPG_VERSION
  - make --directory=extras/kdf-keys
  - sudo make --directory=extras/kdf-keys install

script:
  - make test
